const db=window.supabaseClient;let P=[],C=[],M=[];const $=x=>document.getElementById(x);const esc=x=>String(x??"").replace(/[&<>"']/g,a=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[a]));const st=p=>Number(p.stock_quantity||0);const crit=p=>st(p)<=Number(p.critical_stock||0);
async function load(){try{let[a,b,c]=await Promise.all([db.from("products").select("*").order("name"),db.from("parties").select("*").order("name"),db.from("stock_movements").select("*,products(name,code),parties(name)").order("created_at",{ascending:false}).limit(300)]);if(a.error)throw a.error;if(b.error)throw b.error;if(c.error)throw c.error;P=a.data||[];C=b.data||[];M=c.data||[];render()}catch(e){alert(e.message)}}
function render(){ $("nprod").textContent=P.length;$("ncrit").textContent=P.filter(crit).length;$("nstock").textContent=P.reduce((a,p)=>a+st(p),0);$("nparty").textContent=C.length;
let q=($("search").value||"").toLowerCase(),rows=P.filter(p=>(p.code+" "+p.name).toLowerCase().includes(q));$("ptable").innerHTML=rows.length?`<table><tr><th>Kod</th><th>Ürün</th><th>Stok</th><th>Kritik</th><th>Alış</th><th>Satış</th><th>Durum</th><th></th></tr>${rows.map(p=>`<tr><td>${esc(p.code)}</td><td>${esc(p.name)}</td><td>${st(p)}</td><td>${p.critical_stock}</td><td>${Number(p.purchase_price||0).toFixed(2)} ₺</td><td>${Number(p.sale_price||0).toFixed(2)} ₺</td><td><span class="${crit(p)?"bad":"ok"}">${crit(p)?"Kritik":"Normal"}</span></td><td><button onclick='productForm(${JSON.stringify(p)})'>Düzenle</button></td></tr>`).join("")}</table>`:"<p>Henüz ürün yok.</p>";
let cr=P.filter(crit);$("critical").innerHTML=cr.length?`<table><tr><th>Kod</th><th>Ürün</th><th>Stok</th><th>Kritik</th></tr>${cr.map(p=>`<tr><td>${esc(p.code)}</td><td>${esc(p.name)}</td><td>${st(p)}</td><td>${p.critical_stock}</td></tr>`).join("")}</table>`:"<p>Kritik stok yok 🎉</p>";
$("mtable").innerHTML=M.length?`<table><tr><th>Tarih</th><th>Tür</th><th>Ürün</th><th>Miktar</th><th>Cari</th><th>Açıklama</th></tr>${M.map(m=>`<tr><td>${new Date(m.created_at).toLocaleString("tr-TR")}</td><td>${m.type==="in"?"Giriş":"Çıkış"}</td><td>${esc(m.products?.name)}</td><td>${m.quantity}</td><td>${esc(m.parties?.name||"-")}</td><td>${esc(m.note||"-")}</td></tr>`).join("")}</table>`:"<p>Henüz hareket yok.</p>";
$("ctable").innerHTML=C.length?`<table><tr><th>Ad / Firma</th><th>Telefon</th><th>E-posta</th><th>Not</th></tr>${C.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.phone)}</td><td>${esc(c.email)}</td><td>${esc(c.note)}</td></tr>`).join("")}</table>`:"<p>Henüz cari yok.</p>"}
function nav(p){document.querySelectorAll(".page").forEach(x=>x.classList.add("hide"));$(p).classList.remove("hide");$("title").textContent={home:"Ana Sayfa",products:"Ürünler",moves:"Stok Hareketleri",parties:"Cari / Müşteriler"}[p];document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.p===p));}
document.querySelectorAll(".nav").forEach(x=>x.onclick=()=>nav(x.dataset.p));$("refresh").onclick=load;$("search").oninput=render;
function modal(t,h){$("mtitle").textContent=t;$("form").innerHTML=h;$("modal").classList.remove("hide")}function closeM(){$("modal").classList.add("hide")}
function productForm(p=null){modal(p?"Ürünü Düzenle":"Yeni Ürün",`<div class=formrow><label>Kod</label><input name=code required value="${esc(p?.code)}"></div><div class=formrow><label>Ürün Adı</label><input name=name required value="${esc(p?.name)}"></div><div class=formrow><label>Mevcut Stok</label><input name=stock_quantity type=number value="${p?.stock_quantity??0}"></div><div class=formrow><label>Kritik Stok</label><input name=critical_stock type=number value="${p?.critical_stock??5}"></div><div class=formrow><label>Alış Fiyatı</label><input name=purchase_price type=number step=.01 value="${p?.purchase_price??0}"></div><div class=formrow><label>Satış Fiyatı</label><input name=sale_price type=number step=.01 value="${p?.sale_price??0}"></div><div class=actions><button>Kaydet</button></div>`);$("form").onsubmit=async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));["stock_quantity","critical_stock","purchase_price","sale_price"].forEach(k=>d[k]=Number(d[k]||0));let r=p?await db.from("products").update(d).eq("id",p.id):await db.from("products").insert(d);if(r.error)return alert(r.error.message);closeM();load()}}
function moveForm(){modal("Stok Hareketi",`<div class=formrow><label>Ürün</label><select name=product_id required>${P.map(p=>`<option value=${p.id}>${esc(p.code)} - ${esc(p.name)} (Stok ${st(p)})</option>`).join("")}</select></div><div class=formrow><label>İşlem</label><select name=type><option value=in>Stok Girişi</option><option value=out>Stok Çıkışı</option></select></div><div class=formrow><label>Miktar</label><input name=quantity type=number min=1 required></div><div class=formrow><label>Cari</label><select name=party_id><option value="">Seçme</option>${C.map(c=>`<option value=${c.id}>${esc(c.name)}</option>`).join("")}</select></div><div class=formrow><label>Açıklama</label><textarea name=note></textarea></div><div class=actions><button>Kaydet</button></div>`);$("form").onsubmit=async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target)),q=Number(d.quantity),p=P.find(x=>x.id===d.product_id);if(d.type==="out"&&st(p)<q)return alert("Yetersiz stok");let ns=st(p)+(d.type==="in"?q:-q),r=await db.from("products").update({stock_quantity:ns}).eq("id",p.id);if(r.error)return alert(r.error.message);r=await db.from("stock_movements").insert({product_id:p.id,party_id:d.party_id||null,type:d.type,quantity:q,note:d.note||null});if(r.error)return alert(r.error.message);closeM();load()}}
function partyForm(){modal("Yeni Cari / Müşteri",`<div class=formrow><label>Ad / Firma</label><input name=name required></div><div class=formrow><label>Telefon</label><input name=phone></div><div class=formrow><label>E-posta</label><input name=email type=email></div><div class=formrow><label>Not</label><textarea name=note></textarea></div><div class=actions><button>Kaydet</button></div>`);$("form").onsubmit=async e=>{e.preventDefault();let r=await db.from("parties").insert(Object.fromEntries(new FormData(e.target)));if(r.error)return alert(r.error.message);closeM();load()}}
load();